Kimjun open
hs-1971467-jungchulHwang/OpenSource-Project pull request #3
Opened 2022-11-16 07:57 UTC by hs-1971379-kimjun

확인하시고 승인 부탁드립니다.

2022-11-17 08:29 UTC, hs-1971431-chaesuhyun commented
사진만 보이면 완벽할거 같습니다~~!

2022-11-17 12:23 UTC, hs-1436090-hoseunghwang approved these changes
수고하셨습니다

2022-11-17 16:37 UTC, hs-1971467-jungchulHwang requested changes
오픈소스 파일도 함께 다시 올려주시면 감사하겠습니다

2022-11-17 18:02 UTC, hs-1436090-hoseunghwang commented
좋은 것 같습니다. 내용 보완하시느라 고생하셨습니다.

2022-11-17 18:07 UTC, hs-1971467-jungchulHwang approved these changes
고생하셨습니다

2022-11-18 04:34 UTC, hs-1971431-chaesuhyun approved these changes
수고하셨습니다!!

2022-11-18 04:34 UTC, merged